Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
Total devices: 16 Devices per task: 1
['EPL']
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
    (_, chisq), grads = loss_and_grad(splt_params)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    (_, chisq), grads = loss_and_grad(splt_params)
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
    (_, chisq), grads = loss_and_grad(splt_params)
    loss, params, opt_state = update(params, opt_state)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    loss, params, opt_state = update(params, opt_state)
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
    return func(*args, **kwargs)
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    ans = call(fun, *args)
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
    pmap_computation = lower_parallel_callable(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
                       ^^^^^^^^^^^^^^^^^^^^^^^^
    loss, params, opt_state = update(params, opt_state)
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    return func(*args, **kwargs)
    (_, chisq), grads = loss_and_grad(splt_params)
           ^^^^^^^^^^^^^^^^^^^^^
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
  0%|                                                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]  0%|                                                                                                                                                                                                   | 0/500 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/api.py", line 1880, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 764, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
                                ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1035, in parallel_callable
    pmap_computation = lower_parallel_callable(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/deepsrch/jax_gigalens_kernel/jax-gigalens/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1219, in lower_parallel_callable
    raise ValueError(
jax._src.traceback_util.UnfilteredStackTrace: ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/u1/s/seanjx/gigalens/jax-demo-bigparallel.py", line 247, in <module>
    map_estimate, chi = model_seq.MAP(opt, n_samples=5000,num_steps=500,seed=0)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 67, in MAP
    loss, params, opt_state = update(params, opt_state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/s/seanjx/gigalens/src/gigalens/jax/inference.py", line 56, in update
    (_, chisq), grads = loss_and_grad(splt_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: On multi-host platforms, the input to pmapped functions must have leading axis size equal to the number of local devices if no `devices` argument is specified. Got axis_size=16, num_local_devices=1
srun: error: nid002876: task 7: Exited with exit code 1
srun: Terminating StepId=26931655.0
srun: error: nid003808: tasks 12,14: Exited with exit code 1
srun: error: nid003321: tasks 8,11: Exited with exit code 1
srun: error: nid002633: tasks 0,2: Exited with exit code 1
slurmstepd: error: *** STEP 26931655.0 ON nid002633 CANCELLED AT 2024-06-18T21:19:27 ***
srun: error: nid002876: tasks 4-6: Exited with exit code 1
srun: error: nid002633: tasks 1,3: Exited with exit code 1
srun: error: nid003808: tasks 13,15: Exited with exit code 1
srun: error: nid003321: tasks 9-10: Exited with exit code 1
